modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "berryfix"
version = "${version}"
displayName = "Berry Fix"
authors = "Adi"
description = '''
Makes food always be edible if you're missing hunger. Never accidentally spam berry bushes again :D
'''
#logoFile = ""

[[dependencies.berryfix]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.berryfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.berryfix]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"